# 请把此文件放到脚本的同文件夹中
clash文件输出目录: clash
demo.yaml文件夹路径: demo.yaml
v2ray配置文件路径: v2ray/config.json
trojan配置文件路径: trojan/config.json
trojan-go配置文件路径: trojan-go/config.json
是否更改clash配置: true
是否更改v2ray配置: true
是否更改trojan配置: true
是否更改trojan-go配置: true

users:
  - password: test1
    expire: 2020-02-01
  - password: test2
    expire: 2100-12-31